### ISSUE TITLE
Returns [ERROR] 429 [object Object]

### ISSUE THREAD

**Issue by TristanBrotherton** [timkmecl/codegpt#1]
I was excited to try this extension, but after installing and adding my API key if I ask a question in the panel i get `[ERROR] 429 [object Object]`

**Comment by TristanBrotherton** [comment]
I believe this was because I had not setup billing

**Comment by AndrewPetrov** [comment]
me too. But my key is correct

**Comment by AndrewPetrov** [comment]
@TristanBrotherton  have you managed this error?

**Comment by TristanBrotherton** [comment]
Yes . It was billing related. Add credits to your account.

**Comment by AndrewPetrov** [comment]
> 

I have paid the account, started from today. Isn't it enough? I'm new to this product
