### ISSUE TITLE
Error 400 undefined?

### ISSUE THREAD

**Issue by PierrunoYT** [timkmecl/codegpt#12]
How can I fix this?

**Comment by timkmecl** [comment]
Which model are you trying to use?

**Comment by PierrunoYT** [comment]
I can't see the models because there's no option to change it.

**Comment by timkmecl** [comment]
What do you mean? There should be an option to select which model to use in the extension settings (where you also put your API key)

**Comment by andreas-jjj** [comment]
I get the same error using the ChatGPT and code- models.

**Comment by timkmecl** [comment]
Hi!
OpenAI has unfortunately discontinued the codex models. The method for connecting to ChatGPT has also been changed, so I will remove those options from the menu in the next update. To use ChatGPT, try my other extension https://github.com/timkmecl/chatgpt-vscode
