### ISSUE TITLE
[ERROR] 429 undefined when using Code-davinci/cushman 2

### ISSUE THREAD

**Issue by FeliciaFiction** [timkmecl/codegpt#19]
API key is working, Text-davinci 3 is working fine. 

It looks like one of the requests did get through based on the the usage logging but either it was too slow to respond or I missed that one. Tried with big chunks of code and a simple if-statement.
Language is Powershell (7.3).

From OpenAI:
Usage report:
20:15
Local time: 22 mrt 2023 21:15
text-davinci, 4 requests
1,270 prompt + 624 completion = 1,894 tokens
20:20
Local time: 22 mrt 2023 21:20
code-davinci, 1 request
417 prompt + 86 completion = 503 tokens
20:30
Local time: 22 mrt 2023 21:30
text-davinci, 1 request
672 prompt + 248 completion = 920 tokens

**Comment by timkmecl** [comment]
The codex models were unfortunately discontinued by OpenAI a few weeks ago, so this is probably the cause of your problem. I will remove the models from the menu.
