### ISSUE TITLE
Extension is not working - [ERROR] 429 [object Object]

### ISSUE THREAD

**Issue by selfrefactor** [timkmecl/codegpt#2]
For me the extension is not working and I have API key set.

This is what I get instead of output: `[ERROR] 429 [object Object]`

**Comment by timkmecl** [comment]
Error 429 means Too many requests, so the cause of this is probably OpenAI's rate limiting. Are you maybe using your API keys somewhere else at the same time, or sending new requests before you get a response from the previous one?

**Comment by selfrefactor** [comment]
txs; I will try again, but this should be documented as expected(kind of) error.

**Comment by AndrewPetrov** [comment]
I generated a fresh key and closed all the widows with chat. I have paid the account. And still, see 429 error. what can I do with this?
