### ISSUE TITLE
1.7.0: Seems not to work with GPT-4 (even with PLUS subscription)

### ISSUE THREAD

**Issue by spyro2000** [timkmecl/codegpt#21]
Hello,

after I updated my API key (was deleted after plugin update again), I did the following configuration:

![image](https://user-images.githubusercontent.com/8479925/227225381-b74c907e-eaa1-408f-88e2-471e4b00877c.png)

But the model responses with the following:

![image](https://user-images.githubusercontent.com/8479925/227225514-56b4d7cf-616e-4397-bf12-e62a6cadfc2f.png)

It works via the browser, though:

![image](https://user-images.githubusercontent.com/8479925/227228544-0498ca3e-7ba6-4c58-a530-1571abd0960f.png)

![image](https://user-images.githubusercontent.com/8479925/227229478-7dd07dfe-4400-46e6-9f9c-d4bb934a8373.png)

**Comment by spyro2000** [comment]
I think it might be this problem:
https://community.openai.com/t/when-i-try-the-gpt-4-model-chat-completion-in-api-request-i-get-an-error-that-model-does-not-exist/98850

So does that mean, that every user (!) and not the developer has to join the waiting list...?

**Comment by killinsun** [comment]
@spyro2000 
You look using the JetBrains plugin, don't you?
Unfortunately, this repository is different from https://github.com/carlrobertoh/CodeGPT.
And this repo seems a bit older version for GPT-3, not GPT-3.5 and 4.

**Comment by timkmecl** [comment]
Closed due to this being an unrelated extension
