### ISSUE TITLE
OpenAI API could not process the query

### ISSUE THREAD

**Issue by soroush68** [timkmecl/codegpt#22]
I used codegpt extension in vscode for somedays without any problem. but today it doesn't work. codegpt chat doesn't answer. when I send a msg, it just shows a notif "stop responding" for some moments. When I write a comment and press ctrl+shift+i the window opens at right side but it doesn't work and just says "OpenAI API could not process the query, try selecting the code and using Ask CodeGPT to write your own query"

I have tried reopening vs, reinstalling codegpt, reentering openai key and didn't succeed in solving the problem.

I uninstalled copilot and gitlenz and some other extensions and then this problem occured. I have no idea if it would be related.

**Comment by hitsrich** [comment]
@timkmecl I am also facing the same issue.

**Comment by timkmecl** [comment]
Sorry, I think you have this problem with another extension with the same name as this one. Ther eis no command or error message like that here.
