### ISSUE TITLE
Code difficult to read with Light Theme

### ISSUE THREAD

**Issue by luch1u** [timkmecl/codegpt#27]
When I change the VSCode theme to Light, the code is displayed with dark colors on a dark background.

![Captura de Pantalla 2023-05-03 a la(s) 12 51 34](https://user-images.githubusercontent.com/21696148/235986321-7da11999-4001-4f8b-844d-d9c4987e6abf.png)

**Comment by timkmecl** [comment]
Hi, this is not the repository for the extension from your screenshot, sorry.
