### ISSUE TITLE
[ERROR] 404 undefined

### ISSUE THREAD

**Issue by Marbouh793** [timkmecl/codegpt#37]
Type: <b>Bug</b>

when typing a query for codeGPT I get the error: 404 undefined

Extension version: 1.1.2
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by NickSutton** [comment]
Same here
