### ISSUE TITLE
"Ask CodeGPT" is not working

### ISSUE THREAD

**Issue by xlaming** [timkmecl/codegpt#5]
Actually when you write a text and try to use Ctrl + Shift + I (or by using Ask CodeGPT) it is returning this: 

sk-<<API KEY REMOVED>> API could not process the query, try selecting the code and using Ask CodeGPT to write your own query

**Comment by timkmecl** [comment]
Hi @xlaming, I am not sure this error can be returned by my extension. Are you sure you opened the issue on the right project?

**Comment by timkmecl** [comment]
I believe there is another extension with almost the same name. Check out the screenshots of this one on the front page of the repository, you'll see it's different than the one you're using.
