### ISSUE TITLE
"That Model Does not exist" when select chatGPT

### ISSUE THREAD

**Issue by Luisparr14** [timkmecl/codegpt#6]
## When I tried to use chatGPT it showed me this message
![image](https://user-images.githubusercontent.com/82967045/219787000-73a51200-9863-4313-8f4e-70c803fcab39.png)

**Comment by timkmecl** [comment]
Hi, 
OpenAI has removed the ChatGPT model that was accessible in the same way as GPT3 via the official API. Therefore it cannot be used anymore and the extension returns an error. I will remove this option from menu in the next update. Once the official ChatGPT API is released, it will be added back.
