### ISSUE TITLE
Can't set apiKey 

### ISSUE THREAD

**Issue by Elwazer007** [timkmecl/codegpt#9]
I 've installed the extenstion to vs-code from the marketplace and I 'm trying to set my api key and it gets me this error 

<img width="602" alt="Screenshot 2023-03-01 at 1 15 34 PM" src="https://user-images.githubusercontent.com/28496859/222124136-62af30ac-1d7c-4d09-bf66-ceddb47043ed.png">

Version: 1.72.1 (Universal)
OS : Macos Ventura version 13.0 (M1 Chip)

**Comment by timkmecl** [comment]
Hi, I think you opened the issue in the wrong repo. There is another extension with the same name, there is no command with the name from your screenshot in this extension.
